name: Run Update Paper Links Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"  # Run At 08:00 on Monday

env:
  GITHUB_USER_NAME: Song Jianhui
  GITHUB_USER_EMAIL: songjh2024@stu.xjtu.edu.cn

jobs:
  build:
    name: update
    runs-on: ubuntu-latest
    
    # 添加并发控制（关键修改1）
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 关键修改2：获取完整历史

      - name: Setup Git config
        run: |
          git config --global user.name "${{ env.GITHUB_USER_NAME }}"
          git config --global user.email "${{ env.GITHUB_USER_EMAIL }}"
          git config --global pull.rebase true  # 关键修改3

      - name: Pull latest changes
        run: git pull origin main --strategy-option=ours  # 关键修改4

      - name: Set up Python Env
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxiv requests pyyaml
          
      - name: Run daily arxiv 
        run: python daily_arxiv.py --update_paper_links

      # 关键修改5：替换为更稳定的commit action
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action Automatic Update CV Arxiv Papers"
          file_pattern: |
            README.md 
            docs/cv-arxiv-daily.json 
            docs/cv-arxiv-daily-web.json 
            docs/index.md 
            docs/cv-arxiv-daily-wechat.json 
            docs/wechat.md
          skip_fetch: true
